[build]
  base = "frontend"
  command = "npm run build"
  publish = "frontend/build"

[build.environment]
  REACT_APP_API_URL = "https://intuvizion.onrender.com"
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
